# Generated by Django 5.0.3 on 2024-12-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
