# Generated by Django 5.0.3 on 2024-12-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_billpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='reminder_date',
            field=models.DateField(blank=True, help_text="Required for 'Specific Date' reminders.", null=True),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='reminder_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('specific_date', 'Specific Date')], default='specific_date', max_length=15),
        ),
    ]
