# Generated by Django 5.0.3 on 2024-12-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_billpayment_reminder_date_billpayment_reminder_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billpayment',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='billpayment',
            name='reminder_type',
        ),
    ]
