# Generated by Django 5.0.3 on 2024-12-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_billpayment_reminder_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='billpayment',
            name='last_reminder_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='reminder_category',
            field=models.CharField(choices=[('EMI', 'EMI Payment'), ('Credit Card', 'Credit Card Payment'), ('Insurance', 'Insurance Payment'), ('Tax', 'Tax Payment'), ('General', 'General Payment')], default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='reminder_type',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Specific', 'Specific')], default='Specific', max_length=10),
        ),
    ]
