# Generated by Django 5.1.4 on 2024-12-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_blacklist_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit_card_number',
            field=models.CharField(max_length=16),
        ),
    ]
